apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coherent
  namespace: argocd
spec:
  destination:
    namespace: coho
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/Cohe-rent/coherent.git  # Update if needed
    path: coherent-new  # Make sure this matches your repo structure
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
